CREATE TABLE LOAI (
    ID INT PRIMARY KEY NOT NULL,
    TENLOAI VARCHAR(100)
)

INSERT INTO LOAI VALUES (1, 'Chuck 70')
INSERT INTO LOAI VALUES (2, 'Elevation')
INSERT INTO LOAI VALUES (3, 'Basketball')
INSERT INTO LOAI VALUES (4, 'Life Style')
INSERT INTO LOAI VALUES (5, 'Skateboarding')